version: "3.8"

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: erp
    # volumes:
    #   - /my/mysql/data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - erp-angular
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    command: bash -c "npm run dev"
    ports:
      - "3000:3000"
    networks:
      - erp-angular
    depends_on:
      - mysql
networks:
  erp-angular:
    driver: bridge
