version: "3.8"

services:
  client:
    build:
      context: ./client/erp-web
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    container_name: client
    extra_hosts:
      - "server:192.168.1.12"
    networks:
      erp-angular:
        ipv4_address: 192.168.1.10
    depends_on:
      - server
  mysql:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: database
    restart: always
    # volumes:
    #   - /my/mysql/data:/var/lib/mysql
    networks:
      erp-angular:
        ipv4_address: 192.168.1.11
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    restart: always
    command: bash -c "npm run dev"
    ports:
      - "3000:3000"
    networks:
      erp-angular:
        ipv4_address: 192.168.1.12
    depends_on:
      - mysql
networks:
  erp-angular:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24
