version: "3.8"

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - /my/mysql/data:/var/lib/mysql
    ports:
      - 3306:3306
  # server:
  #   build:
  #     context: ./server
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - db
  #   environment:
  #     - PORT_NODE=3000
  #     - MYSQL_ROOT_PASSWORD=password
